spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    mongodb:
      host: mongodb.tacocloud.com
      port: 27017
      username: tacocoloud
      password: s3cr3tp455w0rd
      database: tacoclouddb